### ISSUE TITLE
Nginx: host not found in upstream.

### ISSUE THREAD

**Issue by ainilili** [caicloud/cyclone#1162]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
cyclone-web is not in ready state after installation using `helm install`
**What you expected to happen**:
I hope it can be used normally
**How to reproduce it (as minimally and precisely as possible)**:
```powershell
helm --debug install --name cyclone --namespace cyclone-system ./helm/cyclone
```
console print.
```
==> v1beta1/Deployment
NAME                         READY  UP-TO-DATE  AVAILABLE  AGE
cyclone-server               1/1    1           1          27m
cyclone-web                  0/1    1           0          27m
cyclone-workflow-controller  1/1    1           1          27m
```
**Anything else we need to know?**:
K8s's version:
```
[root@node2 etc]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
Helm's version:
```
[root@node2 etc]# helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
The cyclone's ``values.yaml`` is:
```
# Image registry where to pull images. 'project' specifies where to pull cyclone images,
# while 'libraryProject' specifies where to pull common images like 'alpine', 'busybox'.
# These two projects can be definitely set to the same value.
imageRegistry:
  registry: docker.io
  project: k8sdevops
  libraryProject: library

# Address of Cyclone server
serverAddress: cyclone-server.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.server.listenPort }}

# Cyclone workflow engine variables
engine:
  images:
    gc: alpine:3.8
    dind: docker:18.03-dind
  gc:
    # Whether enable GC, if set to true, pods would be cleaned after execution finished
    enabled: true
    # The time to wait before cleanup pods when an execution finished
    delaySeconds: 300
    # How many times to retry (include the initial one)
    retry: 1
  limits:
    # Maximum number of execution records to keep for each workflow.
    maxWorkflowRuns: 50
  resourceRequirement:
    default:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  notification:
    url: http://{{ .Values.serverAddress }}/apis/v1alpha1/notifications
  developMode: "true"
  executionContext:
    namespace: cyclone-system
    pvc: cyclone-pvc-system

# Cyclone server variables
server:
  listenAddress: 0.0.0.0
  listenPort: 7099
  nodePort: 30011
  webhookUrlPrefix: http://{{ .Values.serverAddress }}/apis/v1alpha1
  init:
    templates: true
    defaultTenant: true
  openControlCluster: true
  pvc:
    storageClass: ""
    size: 10Gi
  resourceRequirement:
    namespace:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
  storageWatcher:
    reportUrl: http://{{ .Values.serverAddress }}/apis/v1alpha1/storage/usages
    intervalSeconds: 30
    resourceRequirements:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi

# Cyclone web variables
web:
  replicas: 1
  listenPort: 80
  nodePort: 30022
```
All of pods:
```
[root@node2 etc]# kubectl get pods -n cyclone-system
NAME                                          READY   STATUS             RESTARTS   AGE
cyclone-server-9b9c55dd4-kq875                1/1     Running            0          50m
cyclone-web-7d6fc676cd-j9wp4                  0/1     CrashLoopBackOff   14         50m
cyclone-workflow-controller-8d45c8957-cqjmf   1/1     Running            0          50m
```
The describe:
```
[root@node2 etc]# kubectl describe pod cyclone-web-7d6fc676cd-j9wp4 -n cyclone-system
.....
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  51m                  default-scheduler  Successfully assigned cyclone-system/cyclone-web-7d6fc676cd-j9wp4 to node1
  Normal   Pulled     49m (x5 over 51m)    kubelet, node1     Container image "docker.io/k8sdevops/cyclone-web:v1.0.0-alpha" already present on machine
  Normal   Created    49m (x5 over 51m)    kubelet, node1     Created container web
  Normal   Started    49m (x5 over 51m)    kubelet, node1     Started container web
  Warning  BackOff    66s (x222 over 51m)  kubelet, node1     Back-off restarting failed container
````
The error logs:
```
[root@node2 etc]# kubectl logs cyclone-web-7d6fc676cd-j9wp4 -n cyclone-system
2019/06/27 07:21:26 [emerg] 1#1: host not found in upstream "cyclone-server:7099" in /etc/nginx/nginx.conf:9
nginx: [emerg] host not found in upstream "cyclone-server:7099" in /etc/nginx/nginx.conf:9
```
Is there anyone who can help me solve this problem? Orz...
