### ISSUE TITLE
Refactor the design about YAML config

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#206]
I will do a research again, on the existed CI/CD systems.

**Comment by superxi911** [comment]
Welcome back

**Comment by gaocegege** [comment]
## Drone

* https://github.com/drone/drone

YAML is first class in drone and we referred to its design in previous versions, it seems that they migrate the code about pipeline to https://github.com/cncd/pipeline, which is a `Go package implements a container-based pipeline engine`

**Comment by gaocegege** [comment]
## GitLab

### Example YAML Config

```yaml
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/namespace/project

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - ln -svf $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - test
    - build

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o mybinary
    artifacts:
      paths:
        - mybinary
```
